networks:
  app-net:
    name: fb-app-bridge-network

services:
  api:
    container_name: user-filestore-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    environment:
      # Keys below are all fake and can be committed to git
      SECRET_KEY_BASE: 'super_secret'
      MAX_IAT_SKEW_SECONDS: "300"
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: "true"
      SERVICE_TOKEN_CACHE_ROOT_URL: http://runner-service-token-cache-api:3000
      RAILS_DEVELOPMENT_HOSTS: user-filestore-api
      AWS_S3_BUCKET_NAME: moj-formbuilder
      KEY_ENCRYPTION_IV: 1234567890123456
      ENCRYPTION_IV: 1234567890123451
      ENCRYPTION_KEY: a9c12000de36def805e4c2107bd8e910
    networks:
      - app-net

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    networks:
      - app-net
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
