---
# web front-end
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "fb-user-filestore-api-{{ .Values.environmentName }}"
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: "fb-user-filestore-api-{{ .Values.environmentName }}"
        appGroup: "fb-user-filestore"
        fb-service-token-cache-access: "true"
        tier: "frontend"
    spec:
      serviceAccountName: "formbuilder-user-filestore-{{ .Values.environmentName }}"
      containers:
      - name: "fb-user-filestore-api-{{ .Values.environmentName }}"
        image: "754256621582.dkr.ecr.eu-west-2.amazonaws.com/formbuilder/fb-user-filestore-api:{{ .Values.circleSha1 }}"
        volumeMounts:
          - name: tmp-files
            mountPath: /tmp/files
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
        # non-secret env vars
        # defined in config_map.yaml
        resources:
          limits:
            cpu: 300m
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 512Mi
        envFrom:
          - configMapRef:
              name: fb-user-filestore-api-env-{{ .Values.environmentName }}
        env:
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: fb-user-filestore-api-secrets-{{ .Values.environmentName }}
                key: secret_key_base
          - name: KEY_ENCRYPTION_IV
            valueFrom:
              secretKeyRef:
                name: fb-user-filestore-api-secrets-{{ .Values.environmentName }}
                key: key_encryption_iv
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-formbuilder-user-filestore-{{ .Values.environmentName }}
                key: access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-formbuilder-user-filestore-{{ .Values.environmentName }}
                key: secret_access_key
          - name: AWS_S3_BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: s3-formbuilder-user-filestore-{{ .Values.environmentName }}
                key: bucket_name
          - name: ENCRYPTION_IV
            valueFrom:
              secretKeyRef:
                name: fb-user-filestore-api-secrets-{{ .Values.environmentName }}
                key: encryption_iv
          - name: ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                name: fb-user-filestore-api-secrets-{{ .Values.environmentName }}
                key: encryption_key
          - name: SENTRY_DSN
            valueFrom:
              secretKeyRef:
                name: fb-user-filestore-api-secrets-{{ .Values.environmentName }}
                key: sentry_dsn
      volumes:
        - name: tmp-files
          emptyDir: {}